export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_STATE = 'USER_SET_STATE';

export const DETAILS_GET = 'DETAILS_GET';
export const DETAILS_POST = 'DETAILS_POST';
export const DETAILS_SET_STATE = 'DETAILS_SET_STATE';

export const TOGGLE_ORDER_SUMMARY = 'TOGGLE_ORDER_SUMMARY';

export const CONTACT_DEALER_POST = 'CONTACT_DEALER_POST';
export const CONTACT_DEALER_SET_STATE = 'CONTACT_DEALER_SET_STATE';
export const CONTACT_DEALER_GET_VEHICLE = 'CONTACT_DEALER_GET_VEHICLE';
