export default {
  NONE: 'none',
  NOT_EMPTY: 'notEmpty',
  TEXT: 'text',
  NOT_REQUIRED_TEXT: 'notRequiredText',
  NAME: 'name',
  NAME_ADVANCED: 'nameAdvanced',
  POSTCODE: 'postCode',
  PHONE: 'phone',
  ALT_PHONE: 'altPhone',
  DATE: 'date',
  EMAIL: 'email',
  PASSWORD: 'password',
  NUMBER: 'number',
  DEPENDANTS: 'dependants',
  SALARY: 'salary',
  CHECKBOX: 'checkbox',
  SORTCODE: 'sortCode',
  ACCOUNT_NUMBER: 'accountNumber',
  COUNTRY_OF_BIRTH: 'countryofbirth',
};
