export default {
  data: {
    title: '',
    firstName: '',
    lastName: '',
    middleName: '',
    email: '',
    phone: '',
    alternativePhone: '',
    houseName: '',
    houseNumber: '',
    street: '',
    district: '',
    town: '',
    county: '',
    postcode: '',
    company: '',
    maritalStatus: '',
    drivingLicenceType: '',
    validUKPassport: false,
    dependants: '',
    dateOfBirth: '',
    subscribed: false,
  },
  isLoadingGet: false,
  isLoadingPost: false,
  updated: false,
  apiError: false,
};
