# Universal pull of stylelint rules
# Enabled just sass syntax related ones

ignoreFiles: [
  # place files with @each etc. here to avoid a stylelint crash
  "src/components/button/button.module.sass",
  "src/components/typography/typography.module.sass",
]

rules:
  #at-rule-blacklist: true
  at-rule-empty-line-before: always
  #at-rule-name-case: true
  #at-rule-name-newline-after: true
  #at-rule-semicolon-space-before: true
  at-rule-name-space-after: always
  at-rule-no-unknown: true
  at-rule-no-vendor-prefix: true
  #at-rule-semicolon-newline-after: true
  #at-rule-allowed-list: true
  #block-closing-brace-empty-line-before: true
  #block-closing-brace-newline-after: true
  #block-closing-brace-newline-before: true
  #block-closing-brace-space-after: true
  #block-closing-brace-space-before: true
  #block-no-empty: true
  #block-opening-brace-newline-after: true
  #block-opening-brace-newline-before: true
  #block-opening-brace-space-after: true
  #block-opening-brace-space-before: true
  #color-no-hex: true
  color-hex-case: lower
  color-hex-length: short
  color-named: never
  color-no-invalid-hex: true
  comment-empty-line-before: always
  comment-no-empty: true
  comment-whitespace-inside: always
  #comment-word-blacklist: true
  #custom-media-pattern: true
  #custom-property-empty-line-before: true
  #custom-property-pattern: true
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-block-no-duplicate-properties: true
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  #declaration-block-semicolon-newline-after: true
  #declaration-block-semicolon-newline-before: true
  #declaration-block-semicolon-space-after: true
  #declaration-block-semicolon-space-before: true
  declaration-block-single-line-max-declarations: 1
  #declaration-block-trailing-semicolon: true
  #declaration-colon-newline-after: true
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  declaration-empty-line-before: never
  declaration-no-important: true
  #declaration-property-unit-blacklist: true
  #declaration-property-unit-whitelist: true
  #declaration-property-value-blacklist: true
  #declaration-property-value-whitelist: true
  #font-family-no-missing-generic-family-keyword: true
  font-family-name-quotes: always-unless-keyword
  font-family-no-duplicate-names: true
  font-weight-notation:
    - numeric
    - severity: warning
  #function-blacklist: true
  function-calc-no-unspaced-operator: true
  function-comma-newline-after: never-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always
  #function-comma-space-before: true
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case: lower
  #function-parentheses-newline-inside: true
  #function-parentheses-space-inside: true
  #function-url-no-scheme-relative: true
  function-url-quotes: always
  #function-url-scheme-blacklist: true
  #function-url-scheme-whitelist: true
  #function-whitelist: true
  #function-whitespace-after: true
  #keyframe-declaration-no-important: true
  #keyframes-name-pattern: true
  length-zero-no-unit: true
  # linebreaks: true
  max-empty-lines: 1
  #max-line-length: true
  max-nesting-depth: 4 # must be 2...3 maximum
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  #media-feature-name-blacklist: true
  media-feature-name-case: lower
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  #media-feature-name-value-whitelist: true
  #media-feature-name-whitelist: true
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  #media-query-list-comma-newline-after: true
  #media-query-list-comma-newline-before: true
  #media-query-list-comma-space-after: true
  #media-query-list-comma-space-before: true
  #no-descending-specificity: true
  #no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-empty-first-line: true
  no-eol-whitespace: true
  #no-extra-semicolons: true
  #no-invalid-double-slash-comments: true
  no-missing-end-of-source-newline: true
  # no-unknown-animations: true
  number-leading-zero: never
  number-max-precision: 2
  number-no-trailing-zeros: true
  #property-blacklist: true
  property-case: lower
  property-no-unknown: true
  #property-no-vendor-prefix: true
  #property-whitelist: true
  rule-empty-line-before: always
  selector-attribute-brackets-space-inside: never
  #selector-attribute-operator-blacklist: true
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  #selector-attribute-operator-whitelist: true
  selector-attribute-quotes: always
  #selector-class-pattern: true
  #selector-combinator-blacklist: true
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  #selector-combinator-whitelist: true
  selector-descendant-combinator-no-non-space: true
  #selector-id-pattern: true
  #selector-list-comma-newline-after: true
  #selector-list-comma-newline-before: true
  #selector-list-comma-space-after: true
  #selector-list-comma-space-before: true
  #selector-max-attribute: true
  selector-max-class: 3 # too many
  #selector-max-combinators: true
  #selector-max-compound-selectors: true
  selector-max-empty-lines: 0
  selector-max-id: 0
  #selector-max-pseudo-class: true
  #selector-max-specificity: true
  selector-max-type: 2
  selector-max-universal: 2
  #selector-nested-pattern: true
  # selector-no-qualifying-type: true # we need this rule
  selector-no-vendor-prefix: true
  #selector-pseudo-class-blacklist: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-no-unknown: true
  selector-pseudo-class-parentheses-space-inside: always
  #selector-pseudo-class-whitelist: true
  #selector-pseudo-element-blacklist: true
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-pseudo-element-no-unknown: true
  #selector-pseudo-element-whitelist: true
  selector-type-case: lower
  selector-type-no-unknown: true
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  string-quotes: single
  time-min-milliseconds: 100
  #unit-blacklist: true
  unit-case: lower
  unit-no-unknown: true
  #unit-whitelist: true
  value-keyword-case: lower
  value-list-comma-newline-after: never-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  value-no-vendor-prefix: true
  indentation: 2
